# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ced49746ef7814e64ddcf68a32a6bc856fbb5cb8ea41c91eeef5e266fdf85117bb1816eca99c04110db45e41afb7f1bae4966a41701f53bcc05835e81ed0d7b1

test:
  secret_key_base: cf41dda463e435a6ed63b7b972eca0ec447a68f4644e9f66d3e643dd5f5190d0ff169b4b5a5cba72ae1b5a80a3281260f75eee093c500f6d3bb046a5a99904ab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
